exports.data = [
    {
        "bountyId":0,
        "title":"捉拿土豪哥布林",
        "desc":"哥布林中的土豪出现了！趁他们逃跑之前击倒，获得大量金币！",
        "count":3,
        "date":{
            "segment":[
                {
                    "start":"12:00",
                    "end":"23:59"
                }
            ]
        },
        "begin":1,
        "titlePic":"bounty-icon3.png",
        "timePic":"bounty-time3.png",
	"notify":1,
        "notifyButton":"拿下",
        "notifyText":"报⋯⋯！发现一群哥布林土豪，请老大立刻拿下它们！",
         "level":[
            {
                "powerLimit":100,
                "stage":114,
                "prize":[
                    {
                        "type":1
                    }
                ]

            },
            {
                "powerLimit":1400,
                "stage":115,
                "prize":[
                    {
                        "type":1
                    }
                ]
            },
            {
                "powerLimit":5000,
                "stage":116,
                "prize":[
                    {
                        "type":1
                    }
                ]
            }
        ]
    } ,
    {
        "bountyId":1,
        "title":"邪恶头领讨伐令",
        "desc":"邪恶头领聚集起来，讨伐它们获得大量强化石！",
        "count":13,
        "date":{
            "day":[0,2,3,6],
            "segment":[
                {
                    "start":"10:00",
                    "end":"23:59"
                }
            ]
        },
        "begin":1,
        "titlePic":"bounty-icon5.png",
        "timePic":"bounty-time5.png",
        "notify":1,
        "notifyButton":"挑战",
        "notifyText":"邪恶头领又出没了，够胆你就来！",
        "level":[
            {
                "powerLimit":100,
                "stage":114,
                "prize":[
                    {
                        "type":0,
                        "value":853
                    }
                ]

            },
            {
                "powerLimit":400,
                "stage":115,
                "prize":[
                    {
                        "type":0,
                        "value":854
                    }
                ]
            },
            {
                "powerLimit":1700,
                "stage":116,
                "prize":[
                    {
                        "type":0,
                        "value":855
                    }
                ]
            },{
                "powerLimit":3800,
                "stage":114,
                "prize":[
                    {
                        "type":0,
                        "value":856
                    }
                ]

            },
            {
                "powerLimit":5300,
                "stage":115,
                "prize":[
                    {
                        "type":0,
                        "value":857
                    }
                ]
            }
        ]
    }

]