exports.data = [
    {
        "bountyId":0,
        "title":"捉拿土豪哥布林",
        "desc":"哥布林中的土豪出现了！趁他们逃跑之前击倒，获得大量金币！",
        "count":3,
        "date":{
            "segment":[
                {
                    "start":"11:00",
                    "end":"23:59"
                }
            ]
        },
        "begin":1,
        "titlePic":"bounty-icon3.png",
        "timePic":"bounty-time3.png",
         "level":[
            {
                "powerLimit":100,
                "stage":114,
                "prize":[
                    {
                        "type":1
                    }
                ]

            },
            {
                "powerLimit":1000,
                "stage":115,
                "prize":[
                    {
                        "type":1
                    }
                ]
            },
            {
                "powerLimit":3000,
                "stage":116,
                "prize":[
                    {
                        "type":1
                    }
                ]
            }
        ]
    }
]