exports.data = [
    {
        "prizeId":0,
        "itemCld":830
    },
    {
        "prizeId":1,
        "itemCld":831
    },
    {
        "prizeId":2,
        "itemCld":832
    },
    {
        "prizeId":3,
        "itemCld":833
    },
    {
        "prizeId":4,
        "itemCld":834
    },
    {
        "prizeId":5,
        "itemCld":835
    },
    {
        "prizeId":6,
        "itemCld":836,
        "vip":1
    },
    {
        "prizeId":7,
        "itemCld":837
    },
    {
        "prizeId":8,
        "itemCld":838
    },
    {
        "prizeId":9,
        "itemCld":839
    },
    {
        "prizeId":10,
        "itemCld":840
    },
    {
        "prizeId":11,
        "itemCld":841
    },
    {
        "prizeId":12,
        "itemCld":842
    },
    {
        "prizeId":13,
        "itemCld":843,
        "vip":1
    },
    {
        "prizeId":14,
        "itemCld":844
    },
    {
        "prizeId":15,
        "itemCld":845
    },
    {
        "prizeId":16,
        "itemCld":846
    },
    {
        "prizeId":17,
        "itemCld":847
    },
    {
        "prizeId":18,
        "itemCld":848
    },
    {
        "prizeId":19,
        "itemCld":849
    },
    {
        "prizeId":20,
        "itemCld":850,
        "vip":1
    },
    {
        "prizeId":21,
        "itemCld":851
    },
    {
        "prizeId":22,
        "itemCld":852
    },
    {
        "prizeId":23,
        "itemCld":853
    },
    {
        "prizeId":24,
        "itemCld":854
    },
    {
        "prizeId":25,
        "itemCld":855
    },
    {
        "prizeId":26,
        "itemCld":856
    },
    {
        "prizeId":27,
        "itemCld":857,
        "vip":1
    },
    {
        "prizeId":28,
        "itemCld":858
    },
    {
        "prizeId":29,
        "itemCld":859
    },
    {
        "prizeId":30,
        "itemCld":860
    }
]